### ISSUE TITLE
A bunch of changes

### ISSUE THREAD

**Issue by tcolgate** [vbatoufflet/go-livestatus#4]
Heya,
  Just wanted to say that I have a bunch of changes I need to tidy up and raise a PR for on tcolgate/go-livestatus. One of them is a bit large and you may not want it. They are
- KeepAlive support
- Command support

those I think are OK, needs a few comments and tests

The big one is that I've written a little tool to autogenerate bindings for all the nagios external commands to give typed function calls for the all external commands. This bloats the package quite a bit in terms of the external surface area. Not quite sure how to deal with that. take a look at the godoc for tcolgate/go-livestatus and see what you think.
I can maybe move them to a sub package.

**Comment by vbatoufflet** [comment]
Hi,

I welcome all improvements or additional support for this package.

That said, looking at the documentation form your fork, the commands list is quite huge and do bloats the package.

Maybe it could be implemented using variadics (e.g. `func (c *Command) Exec(name string, args ...interface{})`), then calling it like this:

```
c.Exec("CHANGE_CUSTOM_HOST_VAR", "host1.example.net", "foo", "bar")
c.Exec("DISABLE_HOST_EVENT_HANDLER", "host1.example.net")
c.Exec("ENABLE_PERFORMANCE_DATA")
```

WDYT?

**Comment by tcolgate** [comment]
The original implantation looked a bit like that, buy I want a degree of
type safety.
  Theres a raw interface buried in there. How about I leave that at the top
level and add a nagios subpackage with the noise in?
  The awkward thing is that there's no response  on COMMAND at all, so
having a type checked interface is a big win

**Comment by tcolgate** [comment]
Sorry, autocomplete made a right mess of that! Hopefully you got the gist
of it.

**Comment by tcolgate** [comment]
@vbatoufflet I've moved the nagios specific stuff into a sub-package. I'm using a sort of functional option style, but that might be overkill. At present it should work something like

```
lv.Command().Op(nagios.AcknowledgeHostProblem(...))
lv.Exec()
```

which felt a bit more in keeping with the current style.Alternatively it could just be:

```
lv.Command()
nagios.AcknowledgeHostProblem(lv, ....)
lv.Exec()
```

But I don't think that reads as well.

I'll break up the current code into a 3 PRs and send them over (by the end of the week I hope)
