### ISSUE TITLE
Add tags / releases to make go `dep` happy

### ISSUE THREAD

**Issue by riton** [vbatoufflet/go-livestatus#9]
Hi,

We're using `go dep` to manage our internal projects dependencies.

We're not quite comfortable with the fact of using `branch: master` to track your repository as an external dependency. If you introduce breaking changes in your next commits, this would break our build pipelines.

Can you please tag your releases so that we can use _static dependency expression_ in our `Gopkg.toml` file, like in:

```
[[constraint]]
  name = "github.com/vbatoufflet/go-livestatus"
  version = "1.0.0"
```

Thanks in advance !

**Comment by vbatoufflet** [comment]
Hi @riton,

Indeed, it might be useful. I just tagged the first 1.0.0 release.
